### ISSUE TITLE
Aesthetic Improvement

### ISSUE THREAD

**Issue by kstolze6** [kstolze6/DSCMail#9]
### Story/Task Details
- [x] Enchance user registration page
- [x] Enhance main "inbox" page
- [x] Enhance "compose" email page
- [x] Enhance email sent confirmation page
- [x] Give user return to inbox/main page link

### Acceptance Scenarios
- Given: The user wants to feel the software is current and reliable
- When: the user loads their application for the first time
- Then: the user feels the application is easy to navigate and looks familiar and comfortable

### Done Done Criteria
Any improvements are helpful; aesthetic improvements are "done" when the team thinks there's nothing to add and/or final product hand-off.
